## Flight Condition Setup

Here, you will learn how to define static flight conditions (such as altitude, speed, and attitude) and run basic simulations using the previously defined components, solvers, and mass properties.

**Purpose:**
- Set up the environment and conditions for flight simulation.
- Demonstrate how to run a basic simulation and interpret the results.

**What you will learn:**
- How to specify flight conditions for your aircraft.
- How to execute a simulation and analyze the output.




In [1]:
%run ex_mass_properties.ipynb
%run ex_controls.ipynb
%run ex_solvers.ipynb


import csdl_alpha as csdl
import numpy as np
from falco.core.vehicle.conditions import aircraft_conditions
from falco import REPO_ROOT_FOLDER, Q_
import sys
import pandas as pd

Importing OpenVSP file: C:\Users\joeyg\OneDrive\Documents\GitHub\Sarojini_Research\aircraft-flight-simulator\tutorials\geometries\c172.stp
Fuselage: mass_properties is set
Wing: mass_properties is set
Horizontal Tail: mass_properties is set
Vertical Tail: mass_properties is set
Engine: mass_properties is set
Component Mass: [1043.2616] kg
Component CG: [0. 0. 0.] m
Component Inertia: [[1285.3154166    -0.           -0.        ]
 [  -0.         1824.9309607    -0.        ]
 [  -0.           -0.         2666.89390765]]


In [2]:
cruise = aircraft_conditions.CruiseCondition(fd_axis=fd_axis,
                                             controls=c172_controls,
                                             speed=Q_(25, 'm/s'),
                                                altitude=Q_(50, 'ft'),
                                                pitch_angle=Q_(0, 'rad'),
                                                range=Q_(1000, 'm'))


tf, tm = Aircraft_comp.compute_total_loads(fd_state=cruise.ac_states, controls=cruise.controls)
print(tf.value)
print(tm.value)

[2680.69809       0.         9347.15406558]
[-4.45842018e-02  2.96147543e+01  9.03733821e-03]


c:\users\joeyg\onedrive\documents\github\sarojini_research\csdl_alpha\csdl_alpha\src\operations\division.py:19: RuntimeWarning: invalid value encountered in divide
  return x/y
